### ISSUE TITLE
Change Sort on Save to not sort all saved files

### ISSUE THREAD

**Issue by HopperTech** [sixskys/scoped-sort#3] opened 2022-01-19 18:33 UTC
I love the idea of Sort on Save, but started noticing weird changes to files not marked with the { sort-start }  section. 
Didn't realize this would be applied to a whole file if the section was not applied, which is not an expected experience.
I had to turn off this feature and return to manually highlighting and sorting a section. 

Please provide a means of sorting a whole file if the { sort-start } section is not defined.

**Comment by sixskys** [comment] 2022-01-20 04:42
Can you provide some reproducible examples? You are correct that it shouldn't apply any change to files that do not have any sections marked.

I personally don't use sort-on-save since I made a cli app that also sorts sections, but on the times that I did use it I didn't notice anything weird.

> Please provide a means of sorting a whole file if the { sort-start } section is not defined.

Is this related to the first thing or is this a feature request? The main command already sorts the entire file if no text is highlighted.

**Comment by HopperTech** [comment] 2022-01-20 10:57
Sorry I miswrote that comment.

The issue is that all files are being sorted,  even if they do not have a
sort section.  I am requesting that be turned off and only sort files that
have a sort section.  Sorting a file without a sort section causes weird
side effects in files that should not be touched.

**Comment by sixskys** [comment] 2022-01-20 15:56
Yes that is the intention with sort-on-save, it should not be sorting all files. Can you give me one or more reproducible examples so I can see what's going on? I'm not having this issue myself

**Comment by HopperTech** [comment] 2022-01-21 12:48
I have turned this feature back on,  but have not yet reproduced the issue.

I will respond again when I have a reproducible scenario.

**Comment by HopperTech** [comment] 2022-01-27 17:30
I have been able to reproduce the "random sorting" issue.

1) Have VSC auto-save toggled on
2) Have two files opened side-by-side
 - The first has a section that contains a sort section 
 - The second does not
2) make an edit within the sort section 
- Do not manually save this change
3) Click into the other file to edit

The other file (w/o the sort section) is being sorted

**Comment by sixskys** [comment] 2022-01-27 21:22
Alright thanks, was able to reproduce the bug. Will start working on a fix.

**Comment by sixskys** [comment] 2022-01-28 02:55
Fixed in v2.2.0

The problem was that I assumed `vscode.window.activeTextEditor` would always be the file that was being saved, and didn't think about auto save and quickly moving to another file.

**Closed by sixskys** 2022-01-28 02:55 UTC
Labels: bug

**Comment by HopperTech** [comment] 2022-01-28 14:03
Thank you for digging into this.

**Comment by HopperTech** [comment] 2022-01-28 16:21
Just tested the update and it works as expected.
Thank you again for getting to this so quickly.

**Comment by sixskys** [comment] 2022-01-29 03:18
No problem, it was a pretty quick fix.
